### ISSUE TITLE
Strux for Term Set Import??

### ISSUE THREAD

**Issue by fletcherjames** [tb0111/SharepointTools#1]
Hi. I think we could use the Term Set Import in our organization, but would need further assistance. I am an experienced programmer, with some PowerShell skills, but I'm new to SharePoint.

Would you be able to:

a) explain how to prepare the .csv (e.g. what the columns are and how they work in relation to the multi-level structure),

b) tell us what to do in order to create synonym entries, and

c) put a few comments into the code (esp. what the calls to the SP cmdlets do, if they're not obvious.)

Thanks,
Fletcher James

**Comment by fletcherjames** [comment]
P.S. A sample .csv would go a long way towards answering my questions, as long as it dealt with a couple of levels of structure in the Term Set, plus had some Synonyms.

**Comment by TomBayne** [comment]
If you run the Term Set Import the GUI contains an image the will show you how to correctly format the CSV :)
